version: "3"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis-volume:/data"
    command:
      ["redis-server", "--appendonly", "yes", "--requirepass", "changeme"]
    hostname: redis
