version: "3"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis-volume:/data"
    command:
      ["redis-server", "--appendonly", "yes", "--requirepass", "changeme"]
    hostname: redis
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    restart: "always"
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_USER: "plquiz"
      MYSQL_PASSWORD: "changeme"
    volumes:
      - "./mysql-volume:/var/lib/mysql"
      - "./src/init.sql:/data/application/init.sql"
      - "./src/teamplayers.sql:/data/application/teamplayers.sql"
